#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# Keep encoder/query embeddings fixed (precomputed .npy) and train only subgraph reader.
# Keep ReaRev core message passing unchanged, apply TRM-style supervision objective.

RUN_SCRIPT="${RUN_SCRIPT:-trm_rag_style/scripts/run_rearev_d_gpu01_hit06.sh}"

# ReaRev core settings (match baseline behavior).
export SUBGRAPH_RECURSION_STEPS="${SUBGRAPH_RECURSION_STEPS:-4}"
export SUBGRAPH_REAREV_ADAPT_STAGES="${SUBGRAPH_REAREV_ADAPT_STAGES:-2}"
export SUBGRAPH_REAREV_LATENT_REASONING_ENABLED="${SUBGRAPH_REAREV_LATENT_REASONING_ENABLED:-false}"
export SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED="${SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED:-false}"
export SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED="${SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED:-false}"
export SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED="${SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED:-false}"
export SUBGRAPH_REAREV_NORMALIZED_GNN="${SUBGRAPH_REAREV_NORMALIZED_GNN:-false}"

# Disable non-TRM auxiliary objectives.
export SUBGRAPH_DEEP_SUPERVISION_ENABLED="${SUBGRAPH_DEEP_SUPERVISION_ENABLED:-false}"
export SUBGRAPH_DEEP_SUPERVISION_WEIGHT="${SUBGRAPH_DEEP_SUPERVISION_WEIGHT:-0.0}"
export SUBGRAPH_RANKING_ENABLED="${SUBGRAPH_RANKING_ENABLED:-false}"

# TRM-style objective on top of ReaRev core.
export SUBGRAPH_LOSS_MODE="${SUBGRAPH_LOSS_MODE:-rearev_kl_trm}"
export SUBGRAPH_KL_NO_POSITIVE_MODE="${SUBGRAPH_KL_NO_POSITIVE_MODE:-skip}"
export SUBGRAPH_REAREV_TRM_STYLE_ENABLED="${SUBGRAPH_REAREV_TRM_STYLE_ENABLED:-true}"
export SUBGRAPH_REAREV_TRM_TMINUS1_NO_GRAD="${SUBGRAPH_REAREV_TRM_TMINUS1_NO_GRAD:-true}"
export SUBGRAPH_REAREV_TRM_DETACH_CARRY="${SUBGRAPH_REAREV_TRM_DETACH_CARRY:-true}"
export SUBGRAPH_REAREV_TRM_WEIGHT="${SUBGRAPH_REAREV_TRM_WEIGHT:-0.05}"
export SUBGRAPH_REAREV_TRM_CE_WEIGHT="${SUBGRAPH_REAREV_TRM_CE_WEIGHT:-1.0}"
export SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT="${SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT:-1.0}"

echo "[run] ReaRev-core + TRM-style training"
echo "[run] loss_mode=${SUBGRAPH_LOSS_MODE} trm_w=${SUBGRAPH_REAREV_TRM_WEIGHT} ce_w=${SUBGRAPH_REAREV_TRM_CE_WEIGHT} halt_w=${SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT}"
echo "[run] latent=${SUBGRAPH_REAREV_LATENT_REASONING_ENABLED} gate=${SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED} fusion=${SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED} halt=${SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED}"

bash "$RUN_SCRIPT"
