#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"

# Phase1-only run identity
CKPT_DIR="${CKPT_DIR:-trm_agent/ckpt/cwq_trm_hier6_rearev_D_phase1_asym_only_${RUN_TAG}}"
LOG_DIR="${LOG_DIR:-logs/rearev_d_phase1_asym_only_${RUN_TAG}}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-cwq-rearev-D-phase1-asym-only-${RUN_TAG}}"

# GPU/Fallback topology
PRIMARY_GPUS="${PRIMARY_GPUS:-0,1,2,3}"
PRIMARY_NPROC="${PRIMARY_NPROC:-4}"
FALLBACK_GPUS="${FALLBACK_GPUS:-0,1}"
FALLBACK_NPROC="${FALLBACK_NPROC:-2}"
MASTER_PORT="${MASTER_PORT:-29675}"
FALLBACK_MASTER_PORT="${FALLBACK_MASTER_PORT:-29676}"

# Training defaults (phase1 only)
EPOCHS="${EPOCHS:-16}"
BATCH_SIZE="${BATCH_SIZE:-1}"
SUBGRAPH_GRAD_ACCUM_STEPS="${SUBGRAPH_GRAD_ACCUM_STEPS:-8}"
SUBGRAPH_MAX_NODES="${SUBGRAPH_MAX_NODES:-4096}"
SUBGRAPH_MAX_EDGES="${SUBGRAPH_MAX_EDGES:-16384}"

# Asymmetric yz + KL/Halt objective
SUBGRAPH_LOSS_MODE="${SUBGRAPH_LOSS_MODE:-rearev_kl_halt}"
SUBGRAPH_KL_NO_POSITIVE_MODE="${SUBGRAPH_KL_NO_POSITIVE_MODE:-skip}"
SUBGRAPH_KL_SUPERVISION_MODE="${SUBGRAPH_KL_SUPERVISION_MODE:-step_uniform}"
SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED="${SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED:-true}"
SUBGRAPH_REAREV_TRM_STYLE_ENABLED="${SUBGRAPH_REAREV_TRM_STYLE_ENABLED:-true}"
SUBGRAPH_REAREV_TRM_SUPERVISE_ALL_STAGES="${SUBGRAPH_REAREV_TRM_SUPERVISE_ALL_STAGES:-true}"
SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT="${SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT:-1.0}"

# Disable phase2-like ranking/BCE-hardneg behavior for this phase1-only run.
SUBGRAPH_RANKING_ENABLED="${SUBGRAPH_RANKING_ENABLED:-false}"
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="${SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED:-false}"

# ReaRev latent/halting defaults
SUBGRAPH_RECURSION_STEPS="${SUBGRAPH_RECURSION_STEPS:-4}"
SUBGRAPH_REAREV_ADAPT_STAGES="${SUBGRAPH_REAREV_ADAPT_STAGES:-2}"
SUBGRAPH_REAREV_LATENT_REASONING_ENABLED="${SUBGRAPH_REAREV_LATENT_REASONING_ENABLED:-true}"
SUBGRAPH_REAREV_LATENT_RESIDUAL_ALPHA="${SUBGRAPH_REAREV_LATENT_RESIDUAL_ALPHA:-0.25}"
SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED="${SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED:-true}"
SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED="${SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED:-true}"
SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED="${SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED:-true}"
SUBGRAPH_REAREV_DYNAMIC_HALTING_MIN_STEPS="${SUBGRAPH_REAREV_DYNAMIC_HALTING_MIN_STEPS:-3}"
SUBGRAPH_REAREV_DYNAMIC_HALTING_THRESHOLD="${SUBGRAPH_REAREV_DYNAMIC_HALTING_THRESHOLD:-0.95}"

# Phase1-style early stop
SUBGRAPH_EARLY_STOP_ENABLED="${SUBGRAPH_EARLY_STOP_ENABLED:-true}"
SUBGRAPH_EARLY_STOP_METRIC="${SUBGRAPH_EARLY_STOP_METRIC:-dev_hit1}"
SUBGRAPH_EARLY_STOP_PATIENCE="${SUBGRAPH_EARLY_STOP_PATIENCE:-4}"
SUBGRAPH_EARLY_STOP_MIN_DELTA="${SUBGRAPH_EARLY_STOP_MIN_DELTA:-1e-3}"
SUBGRAPH_EARLY_STOP_MIN_EPOCHS="${SUBGRAPH_EARLY_STOP_MIN_EPOCHS:-8}"

# Optional reproducibility/W&B knobs
SEED="${SEED:-42}"
DETERMINISTIC="${DETERMINISTIC:-false}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-graph-traverse}"

echo "[phase1-only] start (asymmetric yz ON, KL+halt)"

PRIMARY_GPUS="$PRIMARY_GPUS" \
PRIMARY_NPROC="$PRIMARY_NPROC" \
FALLBACK_GPUS="$FALLBACK_GPUS" \
FALLBACK_NPROC="$FALLBACK_NPROC" \
MASTER_PORT="$MASTER_PORT" \
FALLBACK_MASTER_PORT="$FALLBACK_MASTER_PORT" \
LOG_DIR="$LOG_DIR" \
CKPT_DIR="$CKPT_DIR" \
WANDB_MODE="$WANDB_MODE" \
WANDB_PROJECT="$WANDB_PROJECT" \
WANDB_RUN_NAME="$WANDB_RUN_NAME" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
SEED="$SEED" \
DETERMINISTIC="$DETERMINISTIC" \
SUBGRAPH_GRAD_ACCUM_STEPS="$SUBGRAPH_GRAD_ACCUM_STEPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_LOSS_MODE="$SUBGRAPH_LOSS_MODE" \
SUBGRAPH_KL_NO_POSITIVE_MODE="$SUBGRAPH_KL_NO_POSITIVE_MODE" \
SUBGRAPH_KL_SUPERVISION_MODE="$SUBGRAPH_KL_SUPERVISION_MODE" \
SUBGRAPH_RANKING_ENABLED="$SUBGRAPH_RANKING_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED" \
SUBGRAPH_RECURSION_STEPS="$SUBGRAPH_RECURSION_STEPS" \
SUBGRAPH_REAREV_ADAPT_STAGES="$SUBGRAPH_REAREV_ADAPT_STAGES" \
SUBGRAPH_REAREV_LATENT_REASONING_ENABLED="$SUBGRAPH_REAREV_LATENT_REASONING_ENABLED" \
SUBGRAPH_REAREV_LATENT_RESIDUAL_ALPHA="$SUBGRAPH_REAREV_LATENT_RESIDUAL_ALPHA" \
SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED="$SUBGRAPH_REAREV_GLOBAL_GATE_ENABLED" \
SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED="$SUBGRAPH_REAREV_LOGIT_GLOBAL_FUSION_ENABLED" \
SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED="$SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED" \
SUBGRAPH_REAREV_DYNAMIC_HALTING_MIN_STEPS="$SUBGRAPH_REAREV_DYNAMIC_HALTING_MIN_STEPS" \
SUBGRAPH_REAREV_DYNAMIC_HALTING_THRESHOLD="$SUBGRAPH_REAREV_DYNAMIC_HALTING_THRESHOLD" \
SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED="$SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED" \
SUBGRAPH_REAREV_TRM_STYLE_ENABLED="$SUBGRAPH_REAREV_TRM_STYLE_ENABLED" \
SUBGRAPH_REAREV_TRM_SUPERVISE_ALL_STAGES="$SUBGRAPH_REAREV_TRM_SUPERVISE_ALL_STAGES" \
SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT="$SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT" \
SUBGRAPH_EARLY_STOP_ENABLED="$SUBGRAPH_EARLY_STOP_ENABLED" \
SUBGRAPH_EARLY_STOP_METRIC="$SUBGRAPH_EARLY_STOP_METRIC" \
SUBGRAPH_EARLY_STOP_PATIENCE="$SUBGRAPH_EARLY_STOP_PATIENCE" \
SUBGRAPH_EARLY_STOP_MIN_DELTA="$SUBGRAPH_EARLY_STOP_MIN_DELTA" \
SUBGRAPH_EARLY_STOP_MIN_EPOCHS="$SUBGRAPH_EARLY_STOP_MIN_EPOCHS" \
bash trm_rag_style/scripts/run_rearev_d_auto_fallback_4to2.sh

echo "[done] phase1-only run finished"
