#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"

CKPT_DIR="${CKPT_DIR:-trm_agent/ckpt/cwq_trm_hier6_trm_frontier_recursive_phase1_${RUN_TAG}}"
LOG_DIR="${LOG_DIR:-logs/trm_frontier_recursive_phase1_${RUN_TAG}}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-cwq-trm-frontier-recursive-phase1-${RUN_TAG}}"

PRIMARY_GPUS="${PRIMARY_GPUS:-0,1,2,3}"
PRIMARY_NPROC="${PRIMARY_NPROC:-4}"
FALLBACK_GPUS="${FALLBACK_GPUS:-0,1}"
FALLBACK_NPROC="${FALLBACK_NPROC:-2}"
MASTER_PORT="${MASTER_PORT:-29931}"
FALLBACK_MASTER_PORT="${FALLBACK_MASTER_PORT:-29932}"

EPOCHS="${EPOCHS:-16}"
BATCH_SIZE="${BATCH_SIZE:-2}"
SUBGRAPH_GRAD_ACCUM_STEPS="${SUBGRAPH_GRAD_ACCUM_STEPS:-4}"
SUBGRAPH_MAX_NODES="${SUBGRAPH_MAX_NODES:-4096}"
SUBGRAPH_MAX_EDGES="${SUBGRAPH_MAX_EDGES:-16384}"

# Frontier-transition recursive block (no stage hierarchy by default).
SUBGRAPH_GNN_VARIANT="${SUBGRAPH_GNN_VARIANT:-trm_frontier_recursive}"
SUBGRAPH_RECURSION_STEPS="${SUBGRAPH_RECURSION_STEPS:-4}"
SUBGRAPH_REAREV_ADAPT_STAGES="${SUBGRAPH_REAREV_ADAPT_STAGES:-1}"
SUBGRAPH_TRM_REL_TOPK_RELATIONS="${SUBGRAPH_TRM_REL_TOPK_RELATIONS:-8}"
SUBGRAPH_TRM_REL_SCORE_ALPHA="${SUBGRAPH_TRM_REL_SCORE_ALPHA:-1.0}"
SUBGRAPH_TRM_REL_USE_RELID_POLICY="${SUBGRAPH_TRM_REL_USE_RELID_POLICY:-true}"

# Final-only KL objective by default (intermediate steps are transition states).
SUBGRAPH_LOSS_MODE="${SUBGRAPH_LOSS_MODE:-rearev_kl}"
SUBGRAPH_KL_NO_POSITIVE_MODE="${SUBGRAPH_KL_NO_POSITIVE_MODE:-skip}"
SUBGRAPH_KL_SUPERVISION_MODE="${SUBGRAPH_KL_SUPERVISION_MODE:-final}"
SUBGRAPH_RANKING_ENABLED="${SUBGRAPH_RANKING_ENABLED:-false}"
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="${SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED:-false}"

# Keep frontier-recursive path simple unless explicitly overridden.
SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED="${SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED:-false}"
SUBGRAPH_REAREV_TRM_STYLE_ENABLED="${SUBGRAPH_REAREV_TRM_STYLE_ENABLED:-false}"
SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED="${SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED:-false}"
SUBGRAPH_DEEP_SUPERVISION_ENABLED="${SUBGRAPH_DEEP_SUPERVISION_ENABLED:-false}"
SUBGRAPH_DDP_FIND_UNUSED_PARAMETERS="${SUBGRAPH_DDP_FIND_UNUSED_PARAMETERS:-true}"

SUBGRAPH_EARLY_STOP_ENABLED="${SUBGRAPH_EARLY_STOP_ENABLED:-true}"
SUBGRAPH_EARLY_STOP_METRIC="${SUBGRAPH_EARLY_STOP_METRIC:-dev_hit1}"
SUBGRAPH_EARLY_STOP_PATIENCE="${SUBGRAPH_EARLY_STOP_PATIENCE:-4}"
SUBGRAPH_EARLY_STOP_MIN_DELTA="${SUBGRAPH_EARLY_STOP_MIN_DELTA:-1e-3}"
SUBGRAPH_EARLY_STOP_MIN_EPOCHS="${SUBGRAPH_EARLY_STOP_MIN_EPOCHS:-8}"

SEED="${SEED:-42}"
DETERMINISTIC="${DETERMINISTIC:-false}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-graph-traverse}"

echo "[phase1-only] start (trm_frontier_recursive, final-KL)"

PRIMARY_GPUS="$PRIMARY_GPUS" \
PRIMARY_NPROC="$PRIMARY_NPROC" \
FALLBACK_GPUS="$FALLBACK_GPUS" \
FALLBACK_NPROC="$FALLBACK_NPROC" \
MASTER_PORT="$MASTER_PORT" \
FALLBACK_MASTER_PORT="$FALLBACK_MASTER_PORT" \
LOG_DIR="$LOG_DIR" \
CKPT_DIR="$CKPT_DIR" \
WANDB_MODE="$WANDB_MODE" \
WANDB_PROJECT="$WANDB_PROJECT" \
WANDB_RUN_NAME="$WANDB_RUN_NAME" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
SEED="$SEED" \
DETERMINISTIC="$DETERMINISTIC" \
SUBGRAPH_GRAD_ACCUM_STEPS="$SUBGRAPH_GRAD_ACCUM_STEPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_GNN_VARIANT="$SUBGRAPH_GNN_VARIANT" \
SUBGRAPH_RECURSION_STEPS="$SUBGRAPH_RECURSION_STEPS" \
SUBGRAPH_REAREV_ADAPT_STAGES="$SUBGRAPH_REAREV_ADAPT_STAGES" \
SUBGRAPH_TRM_REL_TOPK_RELATIONS="$SUBGRAPH_TRM_REL_TOPK_RELATIONS" \
SUBGRAPH_TRM_REL_SCORE_ALPHA="$SUBGRAPH_TRM_REL_SCORE_ALPHA" \
SUBGRAPH_TRM_REL_USE_RELID_POLICY="$SUBGRAPH_TRM_REL_USE_RELID_POLICY" \
SUBGRAPH_LOSS_MODE="$SUBGRAPH_LOSS_MODE" \
SUBGRAPH_KL_NO_POSITIVE_MODE="$SUBGRAPH_KL_NO_POSITIVE_MODE" \
SUBGRAPH_KL_SUPERVISION_MODE="$SUBGRAPH_KL_SUPERVISION_MODE" \
SUBGRAPH_RANKING_ENABLED="$SUBGRAPH_RANKING_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED" \
SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED="$SUBGRAPH_REAREV_DYNAMIC_HALTING_ENABLED" \
SUBGRAPH_REAREV_TRM_STYLE_ENABLED="$SUBGRAPH_REAREV_TRM_STYLE_ENABLED" \
SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED="$SUBGRAPH_REAREV_ASYMMETRIC_YZ_ENABLED" \
SUBGRAPH_DEEP_SUPERVISION_ENABLED="$SUBGRAPH_DEEP_SUPERVISION_ENABLED" \
SUBGRAPH_DDP_FIND_UNUSED_PARAMETERS="$SUBGRAPH_DDP_FIND_UNUSED_PARAMETERS" \
SUBGRAPH_EARLY_STOP_ENABLED="$SUBGRAPH_EARLY_STOP_ENABLED" \
SUBGRAPH_EARLY_STOP_METRIC="$SUBGRAPH_EARLY_STOP_METRIC" \
SUBGRAPH_EARLY_STOP_PATIENCE="$SUBGRAPH_EARLY_STOP_PATIENCE" \
SUBGRAPH_EARLY_STOP_MIN_DELTA="$SUBGRAPH_EARLY_STOP_MIN_DELTA" \
SUBGRAPH_EARLY_STOP_MIN_EPOCHS="$SUBGRAPH_EARLY_STOP_MIN_EPOCHS" \
bash trm_rag_style/scripts/run_rearev_d_auto_fallback_4to2.sh

echo "[done] trm_frontier_recursive phase1 finished"
