#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

export DATASET="${DATASET:-cwq}"
export MODEL_IMPL="${MODEL_IMPL:-trm_hier6}"
export EMB_MODEL="${EMB_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
export EMB_TAG="${EMB_TAG:-$(echo "$EMB_MODEL" | tr '/:' '__' | tr -cd '[:alnum:]_.-')}"
export TORCHRUN="${TORCHRUN:-/data2/workspace/heewon/anaconda3/envs/taiLab/bin/torchrun}"
export NPROC_PER_NODE="${NPROC_PER_NODE:-1}"
export MASTER_PORT="${MASTER_PORT:-29631}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2}"
export TORCH_NCCL_BLOCKING_WAIT="${TORCH_NCCL_BLOCKING_WAIT:-1}"
export DDP_TIMEOUT_MINUTES="${DDP_TIMEOUT_MINUTES:-180}"

export CKPT="${CKPT:-}"
export CKPT_DIR="${CKPT_DIR:-trm_rag_style/ckpt/${DATASET}_${MODEL_IMPL}_2phase_rl}"

export EPOCHS="${EPOCHS:-30}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export LR="${LR:-1e-4}"
export MAX_STEPS="${MAX_STEPS:-4}"
export EVAL_MAX_STEPS="${EVAL_MAX_STEPS:-4}"
export MAX_NEIGHBORS="${MAX_NEIGHBORS:-128}"
export PRUNE_KEEP="${PRUNE_KEEP:-32}"
export PRUNE_RAND="${PRUNE_RAND:-0}"
export EVAL_EVERY_EPOCHS="${EVAL_EVERY_EPOCHS:-2}"
export EVAL_START_EPOCH="${EVAL_START_EPOCH:-2}"
export EVAL_LIMIT="${EVAL_LIMIT:-200}"
export EVAL_PRED_TOPK="${EVAL_PRED_TOPK:-1}"
export EVAL_USE_HALT="${EVAL_USE_HALT:-false}"
export EVAL_NO_CYCLE="${EVAL_NO_CYCLE:-true}"

export WANDB_MODE="${WANDB_MODE:-online}"
export WANDB_PROJECT="${WANDB_PROJECT:-graph-traverse}"
export WANDB_ENTITY="${WANDB_ENTITY:-heewon6205-chung-ang-university}"
export WANDB_RUN_NAME="${WANDB_RUN_NAME:-${DATASET}_2phase_rl_ep${EPOCHS}}"

# Phase-1 supervised warmup
export ENDPOINT_LOSS_MODE="${ENDPOINT_LOSS_MODE:-metric_align_main}"
export RELATION_AUX_WEIGHT="${RELATION_AUX_WEIGHT:-0.2}"
export ENDPOINT_AUX_WEIGHT="${ENDPOINT_AUX_WEIGHT:-0.05}"
export METRIC_ALIGN_AUX_WEIGHT="${METRIC_ALIGN_AUX_WEIGHT:-0.0}"
export HALT_AUX_WEIGHT="${HALT_AUX_WEIGHT:-0.05}"

# Phase-2 RL (SCST)
export PHASE2_START_EPOCH="${PHASE2_START_EPOCH:-11}"
export PHASE2_ENDPOINT_LOSS_MODE="${PHASE2_ENDPOINT_LOSS_MODE:-rl_scst}"
export PHASE2_RELATION_AUX_WEIGHT="${PHASE2_RELATION_AUX_WEIGHT:-0}"
export PHASE2_ENDPOINT_AUX_WEIGHT="${PHASE2_ENDPOINT_AUX_WEIGHT:-0}"
export PHASE2_METRIC_ALIGN_AUX_WEIGHT="${PHASE2_METRIC_ALIGN_AUX_WEIGHT:-0}"
export PHASE2_HALT_AUX_WEIGHT="${PHASE2_HALT_AUX_WEIGHT:-0}"
export PHASE2_RL_REWARD_METRIC="${PHASE2_RL_REWARD_METRIC:-f1}"
export PHASE2_RL_ENTROPY_WEIGHT="${PHASE2_RL_ENTROPY_WEIGHT:-0.01}"
export PHASE2_RL_SAMPLE_TEMP="${PHASE2_RL_SAMPLE_TEMP:-1.0}"
export PHASE2_RL_USE_GREEDY_BASELINE="${PHASE2_RL_USE_GREEDY_BASELINE:-false}"
export PHASE2_RL_NO_CYCLE="${PHASE2_RL_NO_CYCLE:-true}"
export PHASE2_RL_ADV_CLIP="${PHASE2_RL_ADV_CLIP:-1.0}"
export TRAIN_ACC_MODE="${TRAIN_ACC_MODE:-auto}"

export PHASE2_AUTO_ENABLED="${PHASE2_AUTO_ENABLED:-false}"
export DDP_FIND_UNUSED="${DDP_FIND_UNUSED:-true}"

bash trm_rag_style/scripts/run_train.sh
